Repository eclipse-xtext/xtext, pull requests merged in 2023-05, with the labels that each got.

#2645 bootstrap against 2.31.0.M2
  pom.xml
Labels: releng

#2642 also archive rolling logs
  Jenkinsfile
Labels: releng

#2646 Don't run 'Build' GH workflow when tags are pushed
  .github/workflows/maven.yml
Labels: releng

#2654 [#2176] use guice namespace annotations to prepare switch from javax.inject to jakarta.inject in guice
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/linking/LinkingBug421744Test.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/AnnotationValidationTest.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/JUnitMethodReturnTypeValidationTest.xtend
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ValidationBug471580Test.xtend
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/linking/LinkingBug421744Test.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/AnnotationValidationTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/JUnitMethodReturnTypeValidationTest.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/ValidationBug471580Test.java
  org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/AddJunitLibToClasspathQuickfixTest.xtend
  org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/buildpath/JunitLibClasspathAdderTest.xtend
  org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/buildpath/JunitLibClasspathAdderTest.java
  org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/AddJunitLibToClasspathQuickfixTest.java
  org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/IndexedJvmTypeAccessTest.java
  org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/serializer/PartialSerializerTest.java
  org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/util/PositionComparatorTest.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/hierarchy/AbstractHierarchyBuilder.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/DiagnosticModificationContext.java
  org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/codeActions/QuickFixCodeActionService.java
  org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ide/AbstractHierarchyBuilderTest.java
  org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/trace/AbstractInstallDebugInfoMojo.java
  org.eclipse.xtext.testlanguages.ide/src/org/eclipse/xtext/testlanguages/fileAware/ide/refactoring/FileAwareTestLanguageReferenceUpdater.java
  org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/debug/TextRegionsWithTitleToStringTest.java
  org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/regionaccess/internal/RegionAccessBuilderTest.java
  org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHierarchyBuilderTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/encoding/WorkspaceEncodingProviderTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/xmleditor/XmlContentAssistLexerTests.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/xmleditor/XmlHighlightingLexerTests.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/xmleditor/XmlLexerTests.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/XbaseQualifiedNameConverterTest.java
  org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/serializer/SerializerTest.java
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/project/XtextProjectConfig.java
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/fileWizard/TemplateFileWizardFragment.xtend
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/projectWizard/TemplateProjectWizardFragment.xtend
  org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/quickfix/QuickfixProviderFragment2.xtend
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/fileWizard/TemplateFileWizardFragment.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/projectWizard/TemplateProjectWizardFragment.java
  org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/quickfix/QuickfixProviderFragment2.java
  org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/src/org/eclipse/xtext/example/homeautomation/tests/SerializerTest.java
  org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/src/org/eclipse/xtext/example/homeautomation/validation/RuleEngineValidator.java
  org.eclipse.xtext/src/org/eclipse/xtext/linking/lazy/LazyLinkingResource.java
  org.eclipse.xtext/src/org/eclipse/xtext/validation/NamesAreUniqueValidationHelper.java
Labels: releng

#2659 cleanup parent project descriptor after repo merge
  org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
  org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
Labels: releng

#2660 [#2653] Support Browser Dispose Timeouts in Hovers
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/html/DefaultEObjectHoverProvider.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/html/IXtextBrowserInformationControl.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/html/XtextBrowserInformationControl.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/html/XtextBrowserInformationControlAdapter.java
  org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseHoverProvider.java
  org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseInformationControl.java
Labels: new_feature

#2670 harmonized maven-deploy-plugin
  org.eclipse.xtend.maven.parent/pom.xml
  org.eclipse.xtext.dev-bom/pom.xml
  org.eclipse.xtext.maven.parent/pom.xml
Labels: releng

#2673 [#2178] Update to LSP4J 0.21.0
  org.eclipse.xtext.dev-bom/pom.xml
  org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ide/META-INF/MANIFEST.MF
  xtext-latest.target
  xtext-r202203.target
  xtext-r202206.target
  xtext-r202209.target
  xtext-r202212.target
  xtext-r202303.target
Labels: releng

#2675 bootstrap against 2.31.0.M3
  pom.xml
Labels: releng

#2681 regenerated docs
  org.eclipse.xtend.doc/contents/204_activeannotations.html
  org.eclipse.xtext.doc/contents/350_continuous_integration.html
Labels: documentation

#2657 [#2625] prepare Jenkinsfile and Scripts for release builds
  jenkins/release-deploy/Jenkinsfile
  org.eclipse.xtext.p2repository/pom.xml
  pom.xml
  scripts/prepare-for-release.sh
Labels: releng

#2683 remove GA=release from new milestones job
  jenkins/milestone-deploy/Jenkinsfile
Labels: releng

#2684 [#2651] remove old jenkinsfiles
  releng/jenkins/bot-updates/Jenkinsfile
  releng/jenkins/release-prepare-branches/Jenkinsfile
  releng/jenkins/sign-and-deploy/Jenkinsfile
Labels: releng

#2688 [#2687] add missing mwe2.launch.ui to tps
  xtext-latest.target
  xtext-r202203.target
  xtext-r202206.target
  xtext-r202209.target
  xtext-r202212.target
  xtext-r202303.target
Labels: releng

#2682 [#2650] try to provide a working fixVersions script
  fixVersions.sh
  scripts/fixVersions.sh
Labels: releng

#2692 bootstrap against 2.31
  pom.xml
Labels: releng

#2685 [#2184] document milestone and release process
  Builds.md
Labels: documentation, releng

#2695 prepare 2023-06 target
  Jenkinsfile
  xtext-r202306.target
Labels: releng
