Repository eclipse-xtext/xtext, pull requests merged in 2024-04, with the labels that each got.

#2994 Remove deprecated Eclipse-LazyStart headers
  org.eclipse.xtend.doc/META-INF/MANIFEST.MF
  org.eclipse.xtext.doc/META-INF/MANIFEST.MF
Labels: releng

#3006 Fixed ISE when removing a resource from resource set
  org.eclipse.xtext.tests/src/org/eclipse/xtext/enumrules/DetachNodeModelTest.java
  org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/detachable/AbstractDetachableParseResult.java
Labels: bug

#2784 New method `AddParameter` with index in `MutableExecutableDeclaration`
  org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/InsertParameterTest.xtend
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/InsertParameterMiniHelperAnno.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/InsertParameterMiniHelperAnnoProcessor.java
  org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/InsertParameterTest.java
  org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/JvmBasedDeclarations.xtend
  org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/JvmExecutableDeclarationImpl.java
  org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/MutableExecutableDeclaration.java
Labels: new_feature

#3019 update to mwe 2.18.0.M2
  org.eclipse.xtext.dev-bom/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
  org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml
  org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
  xtext-latest.target
  xtext-r202203.target
  xtext-r202206.target
  xtext-r202209.target
  xtext-r202212.target
  xtext-r202303.target
  xtext-r202306.target
  xtext-r202309.target
  xtext-r202312.target
  xtext-r202403.target
Labels: releng

#3017 Support detachable node models in the context of storage aware resources
  org.eclipse.xtext.tests/src/org/eclipse/xtext/enumrules/ResourceStorageTest.java
  org.eclipse.xtext.tests/src/org/eclipse/xtext/nodemodel/serialization/ResourceStorageTest.java
  org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/detachable/CompactStoredNodeModelReader.java
  org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/detachable/CompactStoredNodeModelWriter.java
  org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/detachable/StorageAwareDetachableParseResultWrapper.java
  org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/RootNode.java
  org.eclipse.xtext/src/org/eclipse/xtext/resource/ParseResultWrapper.java
  org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageLoadable.java
  org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageWritable.java
  org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/StorageAwareResource.java
Labels: new_feature
